name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dep
      run: sudo apt install cmake gcc g++
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        cd build
        make